### ISSUE TITLE
Support SQL like Escaping special characters for LQL

### ISSUE THREAD

**Issue by nishantsankhala** [logrange/logrange#101]
Currently LQL doesn't support escape special characters and throws error.

lr>select from pod like 'test\*' where msg contains 'test\\'12345'
 :1:52: invalid quoted string "'test\\\\'": invalid syntax

It'd be really helpful to support this.

**Comment by dspasibenko** [comment]
it is supported. Use double quotes, backslashes should work there . In your example try

`select from pod like 'test*' where msg contains "test'12345" `

or for escaping double quotes:

`select from pod like 'test*' where msg contains "test\"12345" `

**Comment by nishantsankhala** [comment]
Thanks @dspasibenko for the help.
