### ISSUE TITLE
Select: fetch all records from partition called 'test'

### ISSUE THREAD

**Issue by nishantsankhala** [logrange/logrange#103]
Hi,

My objective is to fetch all records from partition called `test`.  LQL what I tried is below
```sql
lr>select from test like "*"
```
But this is fetching all records from all partitions including from `logrange.pipe=__default__` partition.
Even when I give some random partition name like `abc`, LQL gives me same all records as above.
```sql
lr>select from abc like "*"
```

Please let me know if it is the correct way to query.

**Comment by dspasibenko** [comment]
Hi @nishantsankhala, for the form expression you have to provide expression over tags. Partitions don’t have names, they have set of tags. If you would like to select data from all partitions where tag ‘test’ is not empty, you should write:

Select from test != “” ...

In your queries you try all partitions, cause the expression is true for any set of the tags.

**Comment by nishantsankhala** [comment]
Thanks @dspasibenko for you response.
