### ISSUE TITLE
How to setup a logrange cluster

### ISSUE THREAD

**Issue by jieteki** [logrange/logrange#106]
hi, i have read through the docs, but didn't find a guide to setup a logrange cluster. 
So i try to dig into source code to find out, i find there is a `hostRegistry` seems to serve this `cluster` - `hosts` purples. 

As far as i know, every logrange server will invoke this `hostRegistry.Init` to register itself to the backend storage, via `hr.Strg.Create(ctx, r)`, so that through `Hosts()` method, one server can find all other hosts in the cluster.

If this is how logrange cluster work ( correct me if i am wrong), then there is a limitation that all logrange server nodes must `share` a *same*  `storage backend`, such as NFS, or remote block devices, such as Ceph. 

Is this how logrange is designed?

thanks!

**Comment by jieteki** [comment]
ok, this `storage` is a `kv.Storage`, which could be a etcd cluster. By default `inmem.New()` is injected to `hostRegistry` as `kv.Storage` type.


[inmem.New()](https://github.com/logrange/logrange/blob/master/server/server.go#L64)

so i think if i want to setup a real cluster(use etcd to manage hosts registry), i need to modify this `linker.Component` to `etcd.New()`

**Comment by dspasibenko** [comment]
@jieteki you've already closed the question, but I would like to answer. Unfortunately cluster configuration is not supported, yet, but you are right regarding the place where it theoretically should be. Is the cluster configuration is essential for your use-case? How would you consider to use logrange? I would be very appreciate you for the answer. Thanks!

**Comment by jieteki** [comment]
Hi , i am investigating a lightweight logging facility to collect my k8s pod/container logs. 

I have about 10 nodes in the k8s cluster, with 50 containers running in each node. The most widely used logging system is EFK stack, but i think it is a little bit heavy. I don't need its powerful functionality, and don't have enough resource for those components. All i want is to collect those container logs ( so when pods crash , rebuilt, deleted , applied, their historical logs is saved somewhere, for later debugging purples), and logrange seems very lightweight and match my needs well.

For now, logrange clustering mode is not the first concern because of those few nodes, logging loads will not be very high. but for future planning, when k8s cluster scale up to 100 nodes. then single node  deploy maybe a problem, if logrange clustering mode works well at a heavy load, it will be very useful for my use case. (if not, maybe i would have to reserve some resources to deploy a heavy EFK stack)

Thanks!

**Comment by jieteki** [comment]
hi @dspasibenko, is there a roadmap for this project ?

**Comment by dspasibenko** [comment]
@jieteki thanks a lot for sharing your use case. Logrange initially was supposed to be used for the use-case like you described and we know that it has couple production installations for k8s cluster already. 
Unfortunately I needed to get a brake with logrange, but right now have certain plan to continue. Answering your question about the roadmap, yes we have the plan:
1. to work on the product requirements and re-consider some concepts. It relates to stored values and fields
2. To have more stable stand-alone server with better CLI and LQL
3. To have indexes for better search
4. To implement UI for better user experience
5. Public API
6. Cluster and HA. 

I would expect to have 1-5 within next 6 months and start working on the clustering solution after. Something like this. I would be happy to talk about your use-case more, so we would be more helpful with the feature development...

**Comment by jieteki** [comment]
Thanks for sharing your plan! it's a very promising project among those complicated logging solutions. Nice job!👍  
I will keep evaluating it with stand-alone deploy, at aspects such as performance, LQL query efficiency, and so on...

**Comment by vtolstov** [comment]
my use-case:
30-100 microservices each output logs. i have 3 servers that coordinate it. also i have rest api to get logs via some labels in streaming mode.
