### ISSUE TITLE
Truncate fails with "could not delete the partition XXX the size is not 0"

### ISSUE THREAD

**Issue by r0mant** [logrange/logrange#108]
There's been observed a discrepancy between the behavior of the `TRUNCATE` command in a dry run vs real mode.

For instance, in a dry run mode the command returns that it's going to delete 910 sources:

```
root@lr-collector-w9bw2:/# /opt/logrange/lr/lr query --config-file /opt/logrange/lr/config/collect.json 'TRUNCATE DRYRUN MINSIZE 100M MAXDBSIZE 100M'
910 source(s) affected. 
```

However when launched without dry run mode, it doesn't actually remove anything:

```
root@lr-collector-w9bw2:/# /opt/logrange/lr/lr query --config-file /opt/logrange/lr/config/collect.json 'TRUNCATE MINSIZE 100M MAXDBSIZE 100M'
0 source(s) affected. 
```

In the logs of lr-aggregator, the following warning appears over and over again:

```
logrange.partition.Service: deleteJournal(): could not delete the partition 16351A6EC7DC0000DC the size is not 0: 1051859
```

The full lr-aggregator log is attached: [aggre.logs.zip](https://github.com/logrange/logrange/files/5355959/aggre.logs.zip).

**Comment by dspasibenko** [comment]
@r0mant yep, thanks for reporting it. The truncate procedure did not work properly in case of the cumulative size of all journals exceeded the maximum allowed size. A journal could not be removed if it is not empty. Fixed now on the master by v0.1.45 tag.
