### ISSUE TITLE
LA: 2 concecutive calls "select limit 10" when we have more than 50 partitions causes panic

### ISSUE THREAD

**Issue by kbabushkin** [logrange/logrange#88]
[06-17 14:59:06.805] WARN  rpc.querier: query(): Could not get/create a cursor, err=could not get a list of journals for the query select limit 10: Limit exceeds. Expected no more than 50 journals, but at least 51 alredy found  state={Id: 0, Query:"select limit 10", Pos:}
[06-17 14:59:12.268] INFO  rpc.ServerConn{127.0.0.1:56843}: readLoop(): ending
panic: Could not release partition, it was not acquired {tags=file=install.log, exclusive=false, readers=0, Src=15A5FCA3D06D00006D}

goroutine 11 [running]:
github.com/logrange/logrange/pkg/tindex.(*inmemService).Release(0xc0003020a0, 0xc0002a10c0, 0x12)
	/Users/kbabushkin/_gopath/src/github.com/logrange/logrange/pkg/tindex/inmem.go:331 +0x25b
github.com/logrange/logrange/pkg/partition.(*Service).GetJournals(0xc000306000, 0x14c0120, 0xc0000a40c0, 0x0, 0x32, 0x0, 0xc0001992c0, 0xc0002fd440)
	/Users/kbabushkin/_gopath/src/github.com/logrange/logrange/pkg/partition/partition.go:243 +0x1d6
github.com/logrange/logrange/pkg/cursor.(*itfactory).GetJournals(0xc00030a000, 0x14c0120, 0xc0000a40c0, 0x0, 0x32, 0xc000257988, 0xc000257978, 0x10b61b2)
	/Users/kbabushkin/_gopath/src/github.com/logrange/logrange/pkg/cursor/itfactory.go:51 +0x56
github.com/logrange/logrange/pkg/cursor.newCursor(0x14c0120, 0xc0000a40c0, 0x15a91b481fee0000, 0xc00006c8c9, 0xf, 0xc00006c8d9, 0x0, 0x14befa0, 0xc00030a000, 0xc000257bc0, ...)
	/Users/kbabushkin/_gopath/src/github.com/logrange/logrange/pkg/cursor/cursor.go:86 +0x19f
github.com/logrange/logrange/pkg/cursor.(*provider).GetOrCreate(0xc000306070, 0x14c0120, 0xc0000a40c0, 0x15a91b481fee0000, 0xc00006c8c9, 0xf, 0xc00006c8d9, 0x0, 0xc0004a8400, 0xc000257ca8, ...)
	/Users/kbabushkin/_gopath/src/github.com/logrange/logrange/pkg/cursor/provider.go:122 +0xb9
github.com/logrange/logrange/api/rpc.(*ServerQuerier).query(0xc000310000, 0x24a1329e0000000c, 0xc00006c8c0, 0x23, 0x64, 0xc000023680)
	/Users/kbabushkin/_gopath/src/github.com/logrange/logrange/api/rpc/querier.go:121 +0x44f
github.com/logrange/range/pkg/rpc.(*server).call(0xc0001f0040, 0xc014c00c8, 0xc00006c8c0, 0x23, 0x64, 0xc000023680)
	/Users/kbabushkin/_gopath/src/github.com/logrange/range/pkg/rpc/server.go:127 +0x29d
github.com/logrange/range/pkg/rpc.(*ServerConn).readLoop(0xc000023680)
	/Users/kbabushkin/_gopath/src/github.com/logrange/range/pkg/rpc/server.go:182 +0x11a
created by github.com/logrange/range/pkg/rpc.(*server).Serve
	/Users/kbabushkin/_gopath/src/github.com/logrange/range/pkg/rpc/server.go:89 +0x34b

**Comment by dspasibenko** [comment]
fixed by fixing inmem of TIndex implementation
