### ISSUE TITLE
BUILD: build from source installs into "/opt/logrange" and requires sudo access to run

### ISSUE THREAD

**Issue by minxuancao** [logrange/logrange#91]
System: macOS Mojave v10.14.5
Description: 
Following "Building LogRange" in "For Developers", LogRange is installed into "/opt/logrange". To run "logrange start", I must use sudo access.

**Comment by dspasibenko** [comment]
@minxuancao do you think if we add an additional clarification into the doc it would be more helpful?

using sudo for running logrange is not good idea. I would rather create /opt/logrange with the permissions for write for the user who runs logrange.

**Comment by minxuancao** [comment]
Hi, I think this was a problem on my part. I had to go into finder to manually change the access for the /opt folder. Yes, I think it may be helpful to add a hint for this in the future. I could submit a pull request for editing the "For Developers" section. I will close this issue.
