### ISSUE TITLE
Adding custom formats for "DataFormat" in Schema in collect.json

### ISSUE THREAD

**Issue by minxuancao** [logrange/logrange#94]
Currently, "DataFormat" in LogRange's collect.json accepts predifined parser names like "k8json" or "text", which are use in order to extract the needed information (msg, time, etc...).

I would like to create a parser by extending the current k8json parser so that we could further parse the msg content. In collection.json, users could specify the fields he/she is interested in extracting. In the parser, these fields would further parsed and added in the output. If the msg contains a time field and it's parses, then it will replace the "time" in k8json.

```
Collection.json
"Schemas": [
      {
        "PathMatcher": "/*(?:.+/)*(?P<pod>.+)_(?P<ns>.+)_(?P<cname>.+)-(?P<cid>.+)\\..+",
        "DataFormat": "K8JsonCustomFields",
        "Meta": {
          "Tags": {
            "pod": "{pod}",
            "ns": "{ns}",
            "cname": "{cname}",
            "cid": "{cid}"
          },
          "Fields": ["time", "level","uid"]
      }
    ]
```

Below are some test cases:
```
Test case 1:   # log does not contain time field, so we use k8's 
Input:

{"log":"level=info logtype=appLog uid=123 user=abc xyz=pqr test-msg", "stream":"stdout", "time":"2019-07-03T00:05:47.776633567Z"}

Output:

{"msg":"level=info logtype=appLog uid=123 user=abc xyz=pqr test-msg", "stream":"stdout", "ts":"2019-07-03T00:05:47.776633567Z", "level":"info", "uid": "123"}
```
```
Test case 2:  #log contains time field

Input:

{"log":"level=info logtype=appLog uid=123 user=abc xyz=pqr test-msg time=2019-06-02T00:05:47.776633567Z", "stream":"stdout", "time":"2019-07-03T00:05:47.776633567Z"}

Output 

{"msg":"level=info logtype=appLog uid=123 user=abc xyz=pqr test-msg time=2019-06-02T00:05:47.776633567Z", "stream":"stdout", "ts":"2019-06-02T00:05:47.776633567Z", "level":"info", "uid": "123"}
```
```
Test case 3:  #log does not a specified field

Input:

{"log":"level=info logtype=appLog user=abc xyz=pqr test-msg time=2019-06-02T00:05:47.776633567Z", "stream":"stdout", "time":"2019-07-03T00:05:47.776633567Z"}

Output 

{"msg":"level=info logtype=appLog user=abc xyz=pqr test-msg time=2019-06-02T00:05:47.776633567Z", "stream":"stdout", "ts":"2019-06-02T00:05:47.776633567Z", "level":"info", "uid": nil}
```
Any suggestions are welcome!

**Comment by dspasibenko** [comment]
@minxuancao sounds like good idea. Several comments:
1. The [Meta](https://github.com/logrange/logrange/blob/1a4caa46d2cebcc288e871cce43ce717ec9c34be/pkg/scanner/schema.go#L43) structure already has Fields mapping
2. The [Schema](https://github.com/logrange/logrange/blob/1a4caa46d2cebcc288e871cce43ce717ec9c34be/pkg/scanner/schema.go#L29) structure has a regexp for parsing file name 'PathMatcher', how about to add there 'RecordMatcher' reg-exp, which will be applied to every record with a purpose to extract fields you need? 
3. To implement the feature, you need to implement the [Parser](https://github.com/logrange/logrange/blob/1a4caa46d2cebcc288e871cce43ce717ec9c34be/pkg/scanner/parser/parser.go#L30), all implementations are in the same parser package

**Comment by minxuancao** [comment]
```
Collection.json
"Schemas": [
      {
        "PathMatcher": "/*(?:.+/)*(?P<pod>.+)_(?P<ns>.+)_(?P<cname>.+)-(?P<cid>.+)\\..+",
        "DataFormat": "K8JsonCustomFields",
        "RecordMatcher": <record regExp>
        "Meta": {
          "Tags": {
            "pod": "{pod}",
            "ns": "{ns}",
            "cname": "{cname}",
            "cid": "{cid}"
          },
          "Fields": {
              "time": "{time}"
              "level": "{level}"
              "uid": "{uid}"
          }
      }
    ]
```
@dspasibenko I updated the schema. Is this what you mean? With this, I will implement a parser to parse the fields out.

**Comment by dspasibenko** [comment]
@minxuancao yep, I would start with this and then we can make a corrections if there are some inconveniences. Also the fields I would try to get key values from RecordMatcher map first, and if there is no one, will try PathMatcher map then. Just couple cents to the idea...

**Comment by minxuancao** [comment]
Thanks! I will come back with questions if there are any.

**Comment by minxuancao** [comment]
@dspasibenko Just to make sure, I am hoping to parse additional fields from the msg field. I don't quite see why I should get key-val from Record Matcher first. Shouldn't I use PathMatcher first to parse the filename, then use record parser to parse each msg field of the each log in that file?

**Comment by dspasibenko** [comment]
@minxuancao I meant that we have 2 regular expressions - PathMatcher defines a regexp for parsing file names and the RecordMatcher will contain the parser for every record. So when you will apply RecordsMatcher to a line of text, you will receive values for each named group, if it matches. This map you can use for assigning field values.

**Comment by minxuancao** [comment]
Oh, That makes sense. Thanks!

**Comment by minxuancao** [comment]
@dspasibenko for our use case, we will only be writing the msg field of each log in logfmt format(https://brandur.org/logfmt). For parsing the msg field of each log, do you think it makes sense that we use already-existing parsing package (https://godoc.org/github.com/kr/logfmt) rather than writing our own?

**Comment by dspasibenko** [comment]
@minxuancao I don't have any strong objections except a weird license. Also it seems that guys had a fun by "optimizing" the code through "goto" [statements](https://github.com/kr/logfmt/blob/master/scanner.go), looks weird, but I hope it works. In general I am fine with the package.

**Comment by minxuancao** [comment]
@dspasibenko I imported the package and can now parse out the fields. I have been using Meta.Fields in collect.json for specifying fields we are interested in parsing out from msg.

However, I think meta.Fields is written on a file level rather than for every record in the file. Because a meta is written for a file.
```
ev := model.NewEvent(w.desc.File, recs, w.meta, w.confCh)
```
I think I would need to have another field meta.msgFields in collect.json where I specify all the fields to extract from each msg. The format of collect.json would look something like this:
```
"Schemas": [
      {
        "PathMatcher": "/*(?:.+/)*(?P<file>.+\\..+)",
        "DataFormat": "logfmt",
        "Meta": {
          "Tags": {
            "file": "{file}"
          },
          "Fields": {
            "time": "{time}",
            "type": "{file}" ,
            "level": "{level}",
            "traceid": "{traceid}"
          },
          "msgField": ["time","file","level","traceid"]
        }
      }
    ]

```
But I can't figure out how to read in meta.msgFields. I see that we are reading collect.json using 
```
	cfg := &Config{}
	err = json.Unmarshal(data, cfg)
```
I think I must be missing something for reading the fields in collect.json... I also don't know if this is the best way to implement this. I think I could be misusing meta.fields...

**Comment by minxuancao** [comment]
When I tried to use the keys in `meta.Fields` and appending <key>=<val> to` rec.Fields`, `meta.Fields`'s default value would overwrite what I wrote in `rec.Fields`.

**Comment by dspasibenko** [comment]
@minxuancao I think you can use Meta.Fields map for populating individual records. For your example, suppose you have:
```
"Fields": {
            "time": "{time}",
            "type": "{file}" ,
            "level": "{level}",
            "traceid": "{traceid}"
          },
```

and every your records in JSON look like this: 
```
{ "level" : "ERROR", 
  "traceId": "1234", 
  "ts": "10:40", 
 "msg": "Some unexpected error happens"
},
 ...
```

In your parser, you can process each of this JSON record and apply extracted values e.g. `level, traceId, ts, msg...` to the Meta.Fields mapping. For this particular example you will apply  2 fields: `level` and `traceId`. Default mapping like `type` will be applied from another map, which comes from the field Schema. PathMatcher (this is `file` field). 

Regarding the field `msgField` I don't think it is needed. Also, do you take into account that field must be exported (capitalized) to be marshaled/unmarshaled? [Json package ](https://golang.org/pkg/encoding/json/) cannot marshal/unmarshal unexported fields

**Comment by dspasibenko** [comment]
@minxuancao of course you need to change some code around, which currently has different logic...

**Comment by minxuancao** [comment]
@dspasibenko Thanks for the tips! I will try to use meta.Fields then.

**Comment by minxuancao** [comment]
@dspasibenko I opened a pull request for this feature. Could you please take a look to see if any changes need to be made?
